### ISSUE TITLE
play / pause & firefox

### ISSUE THREAD

**Issue by b-jerome** [olivierrr/soundcloud-waveform#1]
Hello,

It seem's the play / pause and mouse hover is not working with firefox. It is working well with IE11 and Chrome. There is no JS error.

**Comment by b-jerome** [comment]
Found a fix using e.clientX instead of e.x in mouseover / mousedown functions. Maybe pageX would be better choice ?

**Comment by olivierrr** [comment]
Does that fix it? @b-jerome

**Comment by b-jerome** [comment]
Yes, using e.clientX fix the issue with firefox. IE, Chrome and Safari are also working.
